export const Socials = [
  {
    name: "Twitter",
    url: "https://x.com/tjrenovatie?s=21",
    key: "twitter",
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/tjrenovatie",
    key: "instagram",
  },
  {
    name: "Facebook",
    url: "https://www.facebook.com/share/1BeVy93MZM/?mibextid=wwXIfr",
    key: "facebook",
  },
  {
    name: "Tiktok",
    url: "https://www.tiktok.com/@tjrenovatie",
    key: "tiktok",
  },
];

export const Routes = [
  {
    name: "Home",
    url: "/",
    key: "home",
  },
  {
    name: "About",
    url: "/about",
    key: "about",
  },
  {
    name: "Diensten",
    url: "/diensten",
    key: "diensten",
  },
  {
    name: "Projects",
    url: "/projects",
    key: "projects",
  },
  {
    name: "Contact",
    url: "/contact",
    key: "contact",
  },
];

export const projects = [
  {
    title: "Project A",
    id: "projecta",
    description:
      "Een herinrichting van een woonkamer met een moderne uitstraling, minimalistisch design en functionele details. De focus lag op comfort, duurzaamheid en esthetiek voor een toekomstgericht interieurdesign.",
    images: [
      "/assets/projects/projecta/1.png",
      "/assets/projects/projecta/2.png",
      "/assets/projects/projecta/3.png",
      "/assets/projects/projecta/4.png",
      "/assets/projects/projecta/5.png",
      "/assets/projects/projecta/6.png",
      "/assets/projects/projecta/7.png",
      "/assets/projects/projecta/8.png",
    ],
    thumbnails: [
      "/assets/projects/projecta/1_thumb.png",
      "/assets/projects/projecta/2_thumb.png",
      "/assets/projects/projecta/3_thumb.png",
      "/assets/projects/projecta/4_thumb.png",
      "/assets/projects/projecta/5_thumb.png",
      "/assets/projects/projecta/6_thumb.png",
      "/assets/projects/projecta/7_thumb.png",
      "/assets/projects/projecta/8_thumb.png",
    ],
  },
  {
    title: "Project B",
    id: "projectb",
    description:
      "Een complete keukenrenovatie waarbij verouderde elementen zijn vervangen door hoogwaardige materialen en een modern design. Praktische oplossingen zorgen voor stijlvol, efficiënt koken en een prachtige uitstraling.",
    images: [
      "/assets/projects/projectb/1.png",
      "/assets/projects/projectb/2.png",
      "/assets/projects/projectb/3.png",
      "/assets/projects/projectb/4.png",
      "/assets/projects/projectb/5.png",
      "/assets/projects/projectb/6.png",
      "/assets/projects/projectb/7.png",
      "/assets/projects/projectb/8.png",
    ],
    thumbnails: [
      "/assets/projects/projectb/1_thumb.png",
      "/assets/projects/projectb/2_thumb.png",
      "/assets/projects/projectb/3_thumb.png",
      "/assets/projects/projectb/4_thumb.png",
      "/assets/projects/projectb/5_thumb.png",
      "/assets/projects/projectb/6_thumb.png",
      "/assets/projects/projectb/7_thumb.png",
      "/assets/projects/projectb/8_thumb.png",
    ],
  },
  {
    title: "Project C",
    id: "projectc",
    description:
      "Een prachtig ontworpen buitenpatio gemaakt met duurzame materialen en een modern ontwerp. Ideaal voor ontspanning, gezellige bijeenkomsten en optimaal genieten van elk seizoen in stijl.",
    images: [
      "/assets/projects/projectc/01.png",
      "/assets/projects/projectc/02.png",
      "/assets/projects/projectc/03.png",
      "/assets/projects/projectc/04.png",
      "/assets/projects/projectc/05.png",
    ],
    thumbnails: [
      "/assets/projects/projectc/01_thumb.png",
      "/assets/projects/projectc/02_thumb.png",
      "/assets/projects/projectc/03_thumb.png",
      "/assets/projects/projectc/04_thumb.png",
      "/assets/projects/projectc/05_thumb.png",
    ],
  },
  {
    title: "Project D",
    id: "projectd",
    description:
      "Een prachtig ontworpen buitenpatio gemaakt met duurzame materialen en een modern ontwerp. Ideaal voor ontspanning, gezellige bijeenkomsten en optimaal genieten van elk seizoen in stijl.",
    images: [
      "/assets/projects/projectd/1.png",
      "/assets/projects/projectd/2.png",
      "/assets/projects/projectd/3.png",
      "/assets/projects/projectd/4.png",
      "/assets/projects/projectd/5.png",
      "/assets/projects/projectd/6.png",
      "/assets/projects/projectd/7.png",
      "/assets/projects/projectd/8.png",
      "/assets/projects/projectd/9.png",
      "/assets/projects/projectd/10.png",
      "/assets/projects/projectd/11.png",
      "/assets/projects/projectd/12.png",
      "/assets/projects/projectd/13.png",
      "/assets/projects/projectd/14.png",
    ],
    thumbnails: [
      "/assets/projects/projectd/1_thumb.png",
      "/assets/projects/projectd/2_thumb.png",
      "/assets/projects/projectd/3_thumb.png",
      "/assets/projects/projectd/4_thumb.png",
      "/assets/projects/projectd/5_thumb.png",
      "/assets/projects/projectd/6_thumb.png",
      "/assets/projects/projectd/7_thumb.png",
      "/assets/projects/projectd/8_thumb.png",
      "/assets/projects/projectd/9_thumb.png",
      "/assets/projects/projectd/10_thumb.png",
      "/assets/projects/projectd/11_thumb.png",
      "/assets/projects/projectd/12_thumb.png",
      "/assets/projects/projectd/13_thumb.png",
      "/assets/projects/projectd/14_thumb.png",
    ],
  },
  {
    title: "Project E",
    id: "projecte",
    description: "Placeholder description for Project E.",
    images: [
      "/assets/projects/projecte/1.png",
      "/assets/projects/projecte/2.png",
      "/assets/projects/projecte/3.png",
      "/assets/projects/projecte/4.png",
      "/assets/projects/projecte/5.png",
      "/assets/projects/projecte/6.png",
      "/assets/projects/projecte/7.png",
      "/assets/projects/projecte/8.png",
      "/assets/projects/projecte/9.png",
      "/assets/projects/projecte/10.png",
      "/assets/projects/projecte/11.png",
      "/assets/projects/projecte/12.png",
      "/assets/projects/projecte/13.png",
    ],
    thumbnails: [
      "/assets/projects/projecte/1_thumb.png",
      "/assets/projects/projecte/2_thumb.png",
      "/assets/projects/projecte/3_thumb.png",
      "/assets/projects/projecte/4_thumb.png",
      "/assets/projects/projecte/5_thumb.png",
      "/assets/projects/projecte/6_thumb.png",
      "/assets/projects/projecte/7_thumb.png",
      "/assets/projects/projecte/8_thumb.png",
      "/assets/projects/projecte/9_thumb.png",
      "/assets/projects/projecte/10_thumb.png",
      "/assets/projects/projecte/11_thumb.png",
      "/assets/projects/projecte/12_thumb.png",
      "/assets/projects/projecte/13_thumb.png",
    ],
  },
  {
    title: "Project F",
    id: "projectf",
    description: "Placeholder description for Project F.",
    images: [
      "/assets/projects/projectf/1.png",
      "/assets/projects/projectf/2.png",
      "/assets/projects/projectf/3.png",
      "/assets/projects/projectf/4.png",
      "/assets/projects/projectf/5.png",
      "/assets/projects/projectf/6.png",
    ],
    thumbnails: [
      "/assets/projects/projectf/1_thumb.png",
      "/assets/projects/projectf/2_thumb.png",
      "/assets/projects/projectf/3_thumb.png",
      "/assets/projects/projectf/4_thumb.png",
      "/assets/projects/projectf/5_thumb.png",
      "/assets/projects/projectf/6_thumb.png",
    ],
  },
  {
    title: "Project G",
    id: "projectg",
    description: "Placeholder description for Project G.",
    images: [
      "/assets/projects/projectg/1.png",
      "/assets/projects/projectg/2.png",
      "/assets/projects/projectg/3.png",
      "/assets/projects/projectg/4.png",
      "/assets/projects/projectg/5.png",
      "/assets/projects/projectg/6.png",
    ],
    thumbnails: [
      "/assets/projects/projectg/1_thumb.png",
      "/assets/projects/projectg/2_thumb.png",
      "/assets/projects/projectg/3_thumb.png",
      "/assets/projects/projectg/4_thumb.png",
      "/assets/projects/projectg/5_thumb.png",
      "/assets/projects/projectg/6_thumb.png",
    ],
  },
  {
    title: "Project H",
    id: "projecth",
    description: "Placeholder description for Project H.",
    images: [
      "/assets/projects/projecth/1.png",
      "/assets/projects/projecth/2.png",
      "/assets/projects/projecth/3.png",
      "/assets/projects/projecth/4.png",
      "/assets/projects/projecth/5.png",
      "/assets/projects/projecth/6.png",
    ],
    thumbnails: [
      "/assets/projects/projecth/1_thumb.png",
      "/assets/projects/projecth/2_thumb.png",
      "/assets/projects/projecth/3_thumb.png",
      "/assets/projects/projecth/4_thumb.png",
      "/assets/projects/projecth/5_thumb.png",
      "/assets/projects/projecth/6_thumb.png",
    ],
  },
  {
    title: "Project I",
    id: "projecti",
    description: "Placeholder description for Project I.",
    images: [
      "/assets/projects/projecti/1.png",
      "/assets/projects/projecti/2.png",
      "/assets/projects/projecti/3.png",
      "/assets/projects/projecti/4.png",
      "/assets/projects/projecti/5.png",
      "/assets/projects/projecti/6.png",
      "/assets/projects/projecti/7.png",
      "/assets/projects/projecti/8.png",
      "/assets/projects/projecti/9.png",
      "/assets/projects/projecti/10.png",
      "/assets/projects/projecti/11.png",
      "/assets/projects/projecti/12.png",
      "/assets/projects/projecti/13.png",
      "/assets/projects/projecti/14.png",
      "/assets/projects/projecti/15.png",
      "/assets/projects/projecti/16.png",
      "/assets/projects/projecti/17.png",
      "/assets/projects/projecti/18.png",
      "/assets/projects/projecti/19.png",
      "/assets/projects/projecti/20.png",
      "/assets/projects/projecti/21.png",
      "/assets/projects/projecti/22.png",
      "/assets/projects/projecti/23.png",
      "/assets/projects/projecti/24.png",
      "/assets/projects/projecti/25.png",
    ],
    thumbnails: [
      "/assets/projects/projecti/1_thumb.png",
      "/assets/projects/projecti/2_thumb.png",
      "/assets/projects/projecti/3_thumb.png",
      "/assets/projects/projecti/4_thumb.png",
      "/assets/projects/projecti/5_thumb.png",
      "/assets/projects/projecti/6_thumb.png",
      "/assets/projects/projecti/7_thumb.png",
      "/assets/projects/projecti/8_thumb.png",
      "/assets/projects/projecti/9_thumb.png",
      "/assets/projects/projecti/10_thumb.png",
      "/assets/projects/projecti/11_thumb.png",
      "/assets/projects/projecti/12_thumb.png",
      "/assets/projects/projecti/13_thumb.png",
      "/assets/projects/projecti/14_thumb.png",
      "/assets/projects/projecti/15_thumb.png",
      "/assets/projects/projecti/16_thumb.png",
      "/assets/projects/projecti/17_thumb.png",
      "/assets/projects/projecti/18_thumb.png",
      "/assets/projects/projecti/19_thumb.png",
      "/assets/projects/projecti/20_thumb.png",
      "/assets/projects/projecti/21_thumb.png",
      "/assets/projects/projecti/22_thumb.png",
      "/assets/projects/projecti/23_thumb.png",
      "/assets/projects/projecti/24_thumb.png",
      "/assets/projects/projecti/25_thumb.png",
    ],
  },
  {
    title: "Project J",
    id: "projectj",
    description: "Placeholder description for Project J.",
    images: [
      "/assets/projects/projectj/1.png",
      "/assets/projects/projectj/2.png",
      "/assets/projects/projectj/3.png",
      "/assets/projects/projectj/4.png",
      "/assets/projects/projectj/5.png",
      "/assets/projects/projectj/6.png",
      "/assets/projects/projectj/7.png",
      "/assets/projects/projectj/8.png",
      "/assets/projects/projectj/9.png",
      "/assets/projects/projectj/10.png",
    ],
    thumbnails: [
      "/assets/projects/projectj/1_thumb.png",
      "/assets/projects/projectj/2_thumb.png",
      "/assets/projects/projectj/3_thumb.png",
      "/assets/projects/projectj/4_thumb.png",
      "/assets/projects/projectj/5_thumb.png",
      "/assets/projects/projectj/6_thumb.png",
      "/assets/projects/projectj/7_thumb.png",
      "/assets/projects/projectj/8_thumb.png",
      "/assets/projects/projectj/9_thumb.png",
      "/assets/projects/projectj/10_thumb.png",
    ],
  },
  {
    title: "Project K",
    id: "projectk",
    description: "Placeholder description for Project K.",
    images: [
      "/assets/projects/projectk/1.png",
      "/assets/projects/projectk/2.png",
      "/assets/projects/projectk/3.png",
      "/assets/projects/projectk/4.png",
      "/assets/projects/projectk/5.png",
      "/assets/projects/projectk/6.png",
      "/assets/projects/projectk/7.png",
      "/assets/projects/projectk/8.png",
      "/assets/projects/projectk/9.png",
      "/assets/projects/projectk/10.png",
      "/assets/projects/projectk/11.png",
      "/assets/projects/projectk/12.png",
      "/assets/projects/projectk/13.png",
      "/assets/projects/projectk/14.png",
      "/assets/projects/projectk/15.png",
      "/assets/projects/projectk/16.png",
      "/assets/projects/projectk/17.png",
      "/assets/projects/projectk/18.png",
      "/assets/projects/projectk/19.png",
      "/assets/projects/projectk/20.png",
      "/assets/projects/projectk/21.png",
      "/assets/projects/projectk/22.png",
      "/assets/projects/projectk/23.png",
      "/assets/projects/projectk/24.png",
      "/assets/projects/projectk/25.png",
      "/assets/projects/projectk/26.png",
    ],
    thumbnails: [
      "/assets/projects/projectk/1_thumb.png",
      "/assets/projects/projectk/2_thumb.png",
      "/assets/projects/projectk/3_thumb.png",
      "/assets/projects/projectk/4_thumb.png",
      "/assets/projects/projectk/5_thumb.png",
      "/assets/projects/projectk/6_thumb.png",
      "/assets/projects/projectk/7_thumb.png",
      "/assets/projects/projectk/8_thumb.png",
      "/assets/projects/projectk/9_thumb.png",
      "/assets/projects/projectk/10_thumb.png",
      "/assets/projects/projectk/11_thumb.png",
      "/assets/projects/projectk/12_thumb.png",
      "/assets/projects/projectk/13_thumb.png",
      "/assets/projects/projectk/14_thumb.png",
      "/assets/projects/projectk/15_thumb.png",
      "/assets/projects/projectk/16_thumb.png",
      "/assets/projects/projectk/17_thumb.png",
      "/assets/projects/projectk/18_thumb.png",
      "/assets/projects/projectk/19_thumb.png",
      "/assets/projects/projectk/20_thumb.png",
      "/assets/projects/projectk/21_thumb.png",
      "/assets/projects/projectk/22_thumb.png",
      "/assets/projects/projectk/23_thumb.png",
      "/assets/projects/projectk/24_thumb.png",
      "/assets/projects/projectk/25_thumb.png",
      "/assets/projects/projectk/26_thumb.png",
    ],
  },
  {
    title: "Project L",
    id: "projectl",
    description: "Placeholder description for Project L.",
    images: [
      "/assets/projects/projectl/1.png",
      "/assets/projects/projectl/2.png",
      "/assets/projects/projectl/3.png",
      "/assets/projects/projectl/4.png",
      "/assets/projects/projectl/5.png",
      "/assets/projects/projectl/6.png",
      "/assets/projects/projectl/7.png",
      "/assets/projects/projectl/8.png",
      "/assets/projects/projectl/9.png",
      "/assets/projects/projectl/10.png",
      "/assets/projects/projectl/11.png",
      "/assets/projects/projectl/12.png",
      "/assets/projects/projectl/13.png",
      "/assets/projects/projectl/14.png",
      "/assets/projects/projectl/15.png",
      "/assets/projects/projectl/16.png",
      "/assets/projects/projectl/17.png",
    ],
    thumbnails: [
      "/assets/projects/projectl/1_thumb.png",
      "/assets/projects/projectl/2_thumb.png",
      "/assets/projects/projectl/3_thumb.png",
      "/assets/projects/projectl/4_thumb.png",
      "/assets/projects/projectl/5_thumb.png",
      "/assets/projects/projectl/6_thumb.png",
      "/assets/projects/projectl/7_thumb.png",
      "/assets/projects/projectl/8_thumb.png",
      "/assets/projects/projectl/9_thumb.png",
      "/assets/projects/projectl/10_thumb.png",
      "/assets/projects/projectl/11_thumb.png",
      "/assets/projects/projectl/12_thumb.png",
      "/assets/projects/projectl/13_thumb.png",
      "/assets/projects/projectl/14_thumb.png",
      "/assets/projects/projectl/15_thumb.png",
      "/assets/projects/projectl/16_thumb.png",
      "/assets/projects/projectl/17_thumb.png",
    ],
  },
  {
    title: "Project M",
    id: "projectm",
    description: "Placeholder description for Project M.",
    images: [
      "/assets/projects/projectm/1.png",
      "/assets/projects/projectm/2.png",
      "/assets/projects/projectm/3.png",
      "/assets/projects/projectm/4.png",
      "/assets/projects/projectm/5.png",
      "/assets/projects/projectm/6.png",
      "/assets/projects/projectm/7.png",
      "/assets/projects/projectm/8.png",
      "/assets/projects/projectm/9.png",
      "/assets/projects/projectm/10.png",
      "/assets/projects/projectm/11.png",
      "/assets/projects/projectm/12.png",
      "/assets/projects/projectm/13.png",
      "/assets/projects/projectm/14.png",
      "/assets/projects/projectm/15.png",
      "/assets/projects/projectm/16.png",
      "/assets/projects/projectm/17.png",
      "/assets/projects/projectm/18.png",
      "/assets/projects/projectm/19.png",
      "/assets/projects/projectm/20.png",
      "/assets/projects/projectm/21.png",
      "/assets/projects/projectm/22.png",
      "/assets/projects/projectm/23.png",
      "/assets/projects/projectm/24.png",
      "/assets/projects/projectm/25.png",
      "/assets/projects/projectm/26.png",
      "/assets/projects/projectm/27.png",
    ],
    thumbnails: [
      "/assets/projects/projectm/1_thumb.png",
      "/assets/projects/projectm/2_thumb.png",
      "/assets/projects/projectm/3_thumb.png",
      "/assets/projects/projectm/4_thumb.png",
      "/assets/projects/projectm/5_thumb.png",
      "/assets/projects/projectm/6_thumb.png",
      "/assets/projects/projectm/7_thumb.png",
      "/assets/projects/projectm/8_thumb.png",
      "/assets/projects/projectm/9_thumb.png",
      "/assets/projects/projectm/10_thumb.png",
      "/assets/projects/projectm/11_thumb.png",
      "/assets/projects/projectm/12_thumb.png",
      "/assets/projects/projectm/13_thumb.png",
      "/assets/projects/projectm/14_thumb.png",
      "/assets/projects/projectm/15_thumb.png",
      "/assets/projects/projectm/16_thumb.png",
      "/assets/projects/projectm/17_thumb.png",
      "/assets/projects/projectm/18_thumb.png",
      "/assets/projects/projectm/19_thumb.png",
      "/assets/projects/projectm/20_thumb.png",
      "/assets/projects/projectm/21_thumb.png",
      "/assets/projects/projectm/22_thumb.png",
      "/assets/projects/projectm/23_thumb.png",
      "/assets/projects/projectm/24_thumb.png",
      "/assets/projects/projectm/25_thumb.png",
      "/assets/projects/projectm/26_thumb.png",
      "/assets/projects/projectm/27_thumb.png",
    ],
  },
  {
    title: "Project N",
    id: "projectn",
    description: "Placeholder description for Project N.",
    images: [
      "/assets/projects/projectn/1.png",
      "/assets/projects/projectn/2.png",
      "/assets/projects/projectn/3.png",
      "/assets/projects/projectn/4.png",
      "/assets/projects/projectn/5.png",
      "/assets/projects/projectn/6.png",
      "/assets/projects/projectn/7.png",
      "/assets/projects/projectn/8.png",
      "/assets/projects/projectn/9.png",
      "/assets/projects/projectn/10.png",
      "/assets/projects/projectn/11.png",
      "/assets/projects/projectn/12.png",
      "/assets/projects/projectn/13.png",
      "/assets/projects/projectn/14.png",
      "/assets/projects/projectn/15.png",
      "/assets/projects/projectn/16.png",
      "/assets/projects/projectn/17.png",
      "/assets/projects/projectn/18.png",
      "/assets/projects/projectn/19.png",
      "/assets/projects/projectn/20.png",
      "/assets/projects/projectn/21.png",
      "/assets/projects/projectn/22.png",
      "/assets/projects/projectn/23.png",
      "/assets/projects/projectn/24.png",
      "/assets/projects/projectn/25.png",
      "/assets/projects/projectn/26.png",
      "/assets/projects/projectn/27.png",
      "/assets/projects/projectn/28.png",
      "/assets/projects/projectn/29.png",
      "/assets/projects/projectn/30.png",
      "/assets/projects/projectn/31.png",
      "/assets/projects/projectn/32.png",
      "/assets/projects/projectn/33.png",
      "/assets/projects/projectn/34.png",
      "/assets/projects/projectn/35.png",
      "/assets/projects/projectn/36.png",
    ],
    thumbnails: [
      "/assets/projects/projectn/1_thumb.png",
      "/assets/projects/projectn/2_thumb.png",
      "/assets/projects/projectn/3_thumb.png",
      "/assets/projects/projectn/4_thumb.png",
      "/assets/projects/projectn/5_thumb.png",
      "/assets/projects/projectn/6_thumb.png",
      "/assets/projects/projectn/7_thumb.png",
      "/assets/projects/projectn/8_thumb.png",
      "/assets/projects/projectn/9_thumb.png",
      "/assets/projects/projectn/10_thumb.png",
      "/assets/projects/projectn/11_thumb.png",
      "/assets/projects/projectn/12_thumb.png",
      "/assets/projects/projectn/13_thumb.png",
      "/assets/projects/projectn/14_thumb.png",
      "/assets/projects/projectn/15_thumb.png",
      "/assets/projects/projectn/16_thumb.png",
      "/assets/projects/projectn/17_thumb.png",
      "/assets/projects/projectn/18_thumb.png",
      "/assets/projects/projectn/19_thumb.png",
      "/assets/projects/projectn/20_thumb.png",
      "/assets/projects/projectn/21_thumb.png",
      "/assets/projects/projectn/22_thumb.png",
      "/assets/projects/projectn/23_thumb.png",
      "/assets/projects/projectn/24_thumb.png",
      "/assets/projects/projectn/25_thumb.png",
      "/assets/projects/projectn/26_thumb.png",
      "/assets/projects/projectn/27_thumb.png",
      "/assets/projects/projectn/28_thumb.png",
      "/assets/projects/projectn/29_thumb.png",
      "/assets/projects/projectn/30_thumb.png",
      "/assets/projects/projectn/31_thumb.png",
      "/assets/projects/projectn/32_thumb.png",
      "/assets/projects/projectn/33_thumb.png",
      "/assets/projects/projectn/34_thumb.png",
      "/assets/projects/projectn/35_thumb.png",
      "/assets/projects/projectn/36_thumb.png",
    ],
  },
];
